name: Create Paperspace Instance

on:
  push:
    branches:
      - main

jobs:
  create-instance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Paperspace CLI
        run: |
          curl -fsSL https://console.paperspace.com/install.sh | sh
          export PAPERSPACE_INSTALL="/home/runner/.paperspace"
          export PATH="$PAPERSPACE_INSTALL/bin:$PATH"
          echo $PATH
          pspace machine start --machineId ${{ secrets.PAPERSPACE_MACHINE_ID }} --apiKey ${{ secrets.PAPERSPACE_API_KEY }}
          

      # Additional steps for configuring the instance and running tests can be added here
